### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by tienvooracht** [justintadlock/custom-content-portfolio#10]
The project details metabox doesn't function as 2 minified files are being called (admin.min.css and edit-project.min.js which don't excist!

Would love to give the plugin a spin (especially since my custom portfolio CPT is based on your "Content Type Standards").

**Comment by justintadlock** [comment]
Yeah, I haven't minified the files yet.  You can roll with `SCRIPT_DEBUG` enabled to get the included non-minified files.
