### ISSUE TITLE
Post Type labels

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/custom-content-portfolio#15]
I was wondering are the labels `views`, `pagination` and `list` correct ones? From my understanding they should be `filter_items_list`, `items_list_navigation` and `items_list`.

[Here is the reference](https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-includes/post.php#L1358).

**Comment by justintadlock** [comment]
Looks like that got changed before the official release.
