### ISSUE TITLE
How to add Portfolio link in Menu admin?

### ISSUE THREAD

**Issue by noraheuer** [justintadlock/custom-content-portfolio#20]
WP 4.7
Theme: Twenty Seventeen
CCP only plugin installed

- no modifications
- one portfolio category
- 2 projects

> You can simply go to "Appearance > Menus > Projects > View All". From there, the first item is the "Projects" archive. Same with any CPT that has an archive and menu support. #13 

I do not see a "Projects" tab? So again, how can I add "Portfolio" to a menu other than adding a custom link?

![screen shot 2017-01-12 at 9 30 56 pm](https://cloud.githubusercontent.com/assets/6789426/21916424/7eb52680-d90e-11e6-8f41-05034205b0fb.png)

**Comment by justintadlock** [comment]
I haven't pushed that change live to the dev branch yet.  It's in my local copy and already addressed.

**Comment by justintadlock** [comment]
I'll try to get all changes pushed live _soonish_.  I've just had other projects I've been busy with as of late.

**Comment by redactuk** [comment]
Did this change make it to repository? as can't see CCP options in Menus section on current version.
