### ISSUE TITLE
Portfolio links in custom menu

### ISSUE THREAD

**Issue by redactuk** [justintadlock/custom-content-portfolio#21]
Apologies for opening new issue but I'm stuggling to find what change is necesary to get portfolio categories and tags to be availalble to add on a custom menu. In issue

https://github.com/justintadlock/custom-content-portfolio/issues/20

You mentioned problem already fixed on your local copy. Can you post what the fix is?

Thanks

**Comment by justintadlock** [comment]
Duplicate of: https://github.com/justintadlock/custom-content-portfolio/issues/20
