### ISSUE TITLE
Tags and Category

### ISSUE THREAD

**Issue by knightknight** [justintadlock/custom-content-portfolio#22]
I'm struggling to find the right code call for displaying `portfolio_category` and `portfolio_tag` taxonomies in my content-portfolio_proejct.php template file. I've found most of them in template-project.php.

I've tried <?php echo ccp_get_tag_taxonomy(); ?> and <?php ccp_get_tag_taxonomy( '<h4 class="entry-title">', '</h4>' ); ?> but it dosn't print the categories or tags just portfolio_category/tag.

**Comment by justintadlock** [comment]
Support is provided for the plugin via [Theme Hybrid](https://themehybrid.com/).  This is the bug and issue tracker.
