### ISSUE TITLE
warning... Only variables should be assigned by reference

### ISSUE THREAD

**Issue by saas786** [justintadlock/custom-content-portfolio#8]
Hi Justin,

I am receiving this warning on line https://github.com/justintadlock/custom-content-portfolio/blob/master/portfolio.php#L133

is passing by reference really necessary here?

or we can remove `&` safely?

**Comment by justintadlock** [comment]
Check latest code: https://github.com/justintadlock/custom-content-portfolio/blob/1.0/portfolio.php#L140

**Comment by saas786** [comment]
cool, thanks.
