### ISSUE TITLE
url meta not saved

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/custom-content-portfolio#9]
I noticed weird issue on 1.0.0 branch. The project `url` meta is somehow not saved in database. The weird thing is that in multisite setup it did save but not basic setups.

**Comment by justintadlock** [comment]
I just rewrote the meta box code. Can you test this commit? https://github.com/justintadlock/custom-content-portfolio/commit/c9e7f671690c5055fab8daee41dd66585a5cf8c0

**Comment by samikeijonen** [comment]
I'll test it today.

**Comment by samikeijonen** [comment]
`get_preview_post_link()` is probably a new function for 4.4 but other than that it's working great.

**Comment by justintadlock** [comment]
Oops! Good catch on that function. I was just copying/pasting from core on the post updated messages. Yep, it's for 4.4: https://core.trac.wordpress.org/changeset/34170 I'll throw in a back-compat check.

Closing since this issue is now fixed.

**Comment by samikeijonen** [comment]
Thanks!
